name: py38
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - _pytorch_select=0.1=cpu_0
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=py38h578d9bd_1
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.7=py38hfbd4bf9_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py38h5eee18b_0
  - dask-core=2022.7.0=py38h06a4308_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - easydict=1.9=py_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf0379b8_106
  - filelock=3.9.0=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py38h0a891b7_1
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2022.11.0=py38h06a4308_0
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gdown=4.6.4=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - ghostscript=9.54.0=h27087fc_2
  - giflib=5.2.1=h5eee18b_1
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.30=pyhd8ed1ab_0
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=6.0.2=h99bc08f_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.33=h166bdaf_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.12.2=nompi_h2386368_101
  - huggingface_hub=0.12.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py38h06a4308_0
  - imageio=2.19.3=py38h06a4308_0
  - imagemagick=7.1.0_61=pl5321h0dc3a92_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib-resources=5.10.2=pyhd8ed1ab_0
  - importlib_resources=5.10.2=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipdb=0.13.11=pyhd8ed1ab_0
  - ipython=8.4.0=py38h578d9bd_0
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py38h43d8883_1
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h5aea950_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.74.1=h606061b_1
  - libglu=9.0.0=he1b5a44_1001
  - libgpg-error=1.46=h620e276_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm15=15.0.7=hadd5161_0
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.7.0=py38h340f60e_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libpq=15.1=h2baec63_3
  - libprotobuf=3.21.12=h3eb15da_0
  - librsvg=2.54.4=h7abd40a_0
  - libsndfile=1.2.0=hb75c966_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=252=h166bdaf_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libva=2.17.0=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib=3.7.0=py38h578d9bd_0
  - matplotlib-base=3.7.0=py38hd6c3c57_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpg123=1.31.2=hcb278e6_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.4=py38h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h27087fc_0
  - nss=3.82=he02c5a1_0
  - numexpr=2.8.3=py38h807cd23_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - opencv=4.7.0=py38h578d9bd_0
  - openh264=2.3.1=h27087fc_1
  - openjpeg=2.5.0=hfec8fc6_2
  - openpyxl=3.0.10=py38h5eee18b_0
  - openssl=1.1.1t=h0b41bf4_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=22.0=py38h06a4308_0
  - pandas=1.4.3=py38h6a678d5_0
  - pango=1.50.12=hd33c08f_1
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathtools=0.1.2=py_1
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=2_h7f98852_perl5
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.3.0=py38hace64e9_1
  - pip=22.3.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - ply=3.11=py_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=4.21.12=py38h8dc9893_0
  - psutil=5.9.4=py38h0a891b7_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=h4ab2085_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-opencv=4.7.0=py38h6f1a3b6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py38ha0d8c90_3
  - pyqt5-sip=12.11.0=py38h8dc9893_3
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pytz=2022.1=py38h06a4308_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0=py38h5eee18b_1
  - qt-main=5.15.6=h18908ee_6
  - readline=8.2=h5eee18b_0
  - regex=2022.10.31=py38h0a891b7_0
  - requests=2.28.1=py38h06a4308_0
  - scikit-image=0.19.3=py38h6a678d5_1
  - scipy=1.10.0=py38h14f4228_0
  - sentry-sdk=1.15.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py38h0a891b7_1
  - setuptools=65.6.3=py38h06a4308_0
  - sip=6.7.7=py38h8dc9893_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=3.0.5=pyh44b312d_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=hcb278e6_0
  - termcolor=2.1.0=py38h06a4308_0
  - tifffile=2020.10.1=py38hdd07704_2
  - timm=0.6.12=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.13.2=py38h5274fd1_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=cpu_py38ha229d99_0
  - tornado=6.2=py38h0a891b7_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - transformers=4.24.0=py38h06a4308_0
  - typing-extensions=4.4.0=py38h06a4308_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - unicodedata2=15.0.0=py38h0a891b7_0
  - urllib3=1.26.14=py38h06a4308_0
  - wand=0.6.10=pyhd8ed1ab_0
  - wandb=0.13.10=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.12.1=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
prefix: /home/jtian73/miniconda3/envs/py38
